# Generated by Django 5.1.3 on 2024-12-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.SmallIntegerField(choices=[('InformationTechnology', 'Information Technology'), ('ComputerScience', 'Computer Science'), ('InformationScience', 'Information Science'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical', 'Mechanical')], default=3),
        ),
    ]
