# Generated by Django 5.1.3 on 2024-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0002_alter_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.SmallIntegerField(choices=[(1, 'Information Technology'), (2, 'Computer Science'), (3, 'Information Science'), (4, 'Electronics and Communication'), (5, 'Mechanical')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.SmallIntegerField(choices=[(1, 'Federal Institute'), (2, 'FASF'), (3, 'Harverd')]),
        ),
    ]
