# Generated by Django 5.1.3 on 2024-12-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_alter_profile_branch_alter_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.SmallIntegerField(choices=[(1, 'Federal Institute'), (2, 'FASF'), (3, 'Harverd')], default=1),
        ),
    ]
